# Generated by Django 4.1.3 on 2022-11-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=100)),
                ("team_kpi", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User_Role",
            fields=[
                ("role_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=200)),
                ("fname", models.CharField(max_length=200)),
                ("lname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("ph_no", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aiesec.user_role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="President",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aiesec.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team_Member",
            fields=[
                (
                    "username_M",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="aiesec.user",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="aiesec.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team_Leader",
            fields=[
                (
                    "username_l",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="aiesec.user",
                    ),
                ),
                (
                    "username_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aiesec.president",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="username_l",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aiesec.team_leader"
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=100)),
                ("task_desc", models.CharField(max_length=500)),
                ("due_date", models.DateField()),
                ("status", models.CharField(max_length=200)),
                ("org_name", models.CharField(max_length=100)),

                ("org_email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=200)),
                ("sdg_no", models.CharField(max_length=15)),
                (
                    "username_L",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aiesec.team_leader",
                    ),
                ),
                (
                    "username_M",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aiesec.team_member",
                    ),
                ),
            ],
        ),
    ]
